language: cpp
git:
  depth: 1

matrix:
  fast_finish: false
  include:

  - os: linux
    dist: trusty
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    sudo: required
    env: TARGET="trusty"

#- os: linux
#    dist: trusty
#    sudo: required
#    env: TARGET="yakkety"
#    services: docker

  - os: osx
    compiler:
      - clang
      - gcc
    env: TARGET="osx"
    osx_image: 
      - xcode6.4
      - xcode7
      - xcode7.1
      - xcode7.2
      - xcode7.3
      - xcode8

install:
  - if [ "$TARGET" == "trusty" ]; then
      tools/ci/$TARGET/dependencies.sh;
    fi

script:
  - tools/ci/cmake.sh -DCINDER_BUILD_SAMPLES:BOOL=1 && make check