language: cpp
git:
  depth: 1

fast_finish: false

matrix:
  
  # OS X has no version unique dependencies, so we are able to use matrix
  os: osx
  
  compiler:
    - clang
    - gcc

  osx_image: 
    - xcode6.4
    - xcode7
    - xcode7.1
    - xcode7.2
    - xcode7.3
    - xcode8

  include:

    # linux version have unique dependencies, so we set them up individually
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      sudo: required
      env: TARGET="trusty"

#- os: linux
#    dist: trusty
#    sudo: required
#    env: TARGET="yakkety"
#    services: docker

install:
  - if [ "$TARGET" == "trusty" ]; then
      tools/ci/"$TARGET"_dependencies.sh;
    fi

script:
  # TODO build and test in OS X
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      tools/osx/osx_build_test.sh;
    else
      tools/ci/cmake_test.sh;
    fi