language: cpp
git:
  depth: 1

fast_finish: false

matrix:
  include:

    # linux version have unique dependencies, so we set them up individually
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      sudo: required
      env: TARGET="trusty"

# TODO figure out docker support
#- os: linux
#    dist: trusty
#    sudo: required
#    env: TARGET="yakkety"
#    services: docker

    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      tools/linux/scripts/"$TARGET"-install-deps.sh;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update && brew install cmake;
    fi

script:
  - tools/ci/cmake_test.sh;
    